### ISSUE TITLE
Bleeding edge builds are not signed

### ISSUE THREAD

**Issue by beast01** [citra-emu/citra-bleeding-edge#12]
Tried to open setup and windows smartscreen said its dangerous and has no publisher, Chose to not run, Is it safe?

**Comment by jroweboy** [comment]
yes, its safe. smartscreen is complaining that i haven't signed the binaries yet... but binary signing doesn't add too much security anyway. I mean it is nice to have, but its not necessary yet. 

its on the long list of things to do.
