### ISSUE TITLE
...

### ISSUE THREAD

**Issue by beast01** [citra-emu/citra-bleeding-edge#13]
So 10 minutes after installing citra bleedingedge build 68, my computer started to freeze really bad, I think it's because of a malicious site i went to that claimed to have a pokemon y rom that my antivirus detected the website was just malicious itself. But idk if it was citra or the website. So ye. Maybe it has to do with citra? I ended up rebooting my pc after this btw, pc was fine again after it.

**Comment by jroweboy** [comment]
This is not a support forum. This is a tracker for actual issues about bleeding edge (your other report is an actual issue) but this one is not citras fault.
