### ISSUE TITLE
Mario and Luigi: Dream Team crashes in the Dozing-Sand Desert Dream World when chasing the Dream Stone spirit,

### ISSUE THREAD

**Issue by YouthJeff** [citra-emu/citra-bleeding-edge#25]
When playing through the Dozing-Sand Desert Dream World, whenever you encounter the dream spirit. It would just crash and so when fighting the big boss mode when it ends it. Using a Bleeding Edge Build because I couldn't use the nightly build one. Version: Build number 116 The way to fix this is to turn off Hardware Renderer, but it just so slow and couldn't be playable. Even when you beat the big boss fight using Hardware Renderer. It still crashes.

![image](https://cloud.githubusercontent.com/assets/24926127/21663932/2142addc-d298-11e6-8c87-87005484e97d.png)

**Comment by Dragios** [comment]
Bad crash report. The image alone does not contribute any useful info for the developers.
Where is the crash log? Backtrace?
If you do not know how to submit a crash report, please ask others before attempt to create one.

**Comment by JayFoxRox** [comment]
Use the forums instead: https://community.citra-emu.org/
