### ISSUE TITLE
Error on citra 116 update it to 0.1.158 same as 116 emu so is little different

### ISSUE THREAD

**Issue by Erroronpokemonsun116citrapleasehelp** [citra-emu/citra-bleeding-edge#27]
Because it's getting me mad soon I need to get further in the game why is it a black screen after I battle the professor talk the 1 screen is ok but the 2 black screen isn't I have played Pokémon sun long time I have get to elite four battle all 4 finish them after I go down too be a champion first sit down after coming the professor battle finished him after that talk first black screen is ok after the 2'nd black screen poof error shows up oh yeah when the 2'nd black screen show I need too restart the game another time after I close it when your guys fix this play the Pokémon Sun too take all after coming too point island take all there after go too next finished there all finished go too last thing battle elite 4 finish there so u see too talk or battle professor after you finally talk this happens a 2'nd black screen can't do nothing it's freezing or what is it stubborn it's installed on c the PC system

Please citra do something about it I need too coming further I standing here can't do nothing about it s 
![img_20170127_215819](https://cloud.githubusercontent.com/assets/25392469/22387420/de9483c4-e4db-11e6-842c-8d4e56175be2.jpg)

 
![img_20170127_212404](https://cloud.githubusercontent.com/assets/25392469/22386629/4b5b9c80-e4d8-11e6-9b36-45e85504d33d.jpg)

**Comment by chris062689** [comment]
Please use our Citra Community forums to report issues like this, use the support category and fill out the entire template. 
Please also break up your sentence into steps, we don't understand what you are saying. 
Thanks!

**Comment by Erroronpokemonsun116citrapleasehelp** [comment]
i tell you the error in pokemon sun 
is when i battle professor after 
i finish battle i need to talk
after talk show me 1 black screen is ok but the 2 black screen isn't 
Because after i finish talking too the professor after that poof error promblem
