### ISSUE TITLE
Bleeding Edge 230 - libicuin57.dll error

### ISSUE THREAD

**Issue by Schplee** [citra-emu/citra-bleeding-edge#32]
![xch8ukc](https://cloud.githubusercontent.com/assets/24275329/23347945/f78cfc12-fc73-11e6-8609-fe2b7103cc4d.png)

Seems like it's a simple typo. Previous versions of Citra include libicuin**56** instead of 57.

**Comment by JayFoxRox** [comment]
Was this fixed yet?

**Comment by Schplee** [comment]
@JayFoxRox Yes, Jrowe forgot to close this like I asked >_>
