### ISSUE TITLE
Any chance of distributing bleeding-edge builds in .zip archives also?

### ISSUE THREAD

**Issue by SigmaVirus** [citra-emu/citra-bleeding-edge#33]
My gaming rig is completely offline and I don't want to "install" new versions of the bleeding-edge builds every time I want to try new builds out since it adds clutter.

A simple .zip file archive that can be extracted would very much suffice.

Thanks in advance!

**Comment by RavenHome1** [comment]
you can do that. just download the full .nupkg from github and rename the extension to .zip and you can extract it to get the bleeding edge build

**Comment by SigmaVirus** [comment]
Thanks for the information @RavenHome1, it worked.

You probably want to add that information somewhere so people like me who thought it was a Linux package know it's possible to rename the .nupkg extension to .zip extension.

Closed!

**Comment by jroweboy** [comment]
Portable zip files are planned for the future when i finish the unified updater. (The goal is to rewrite the updater with a different library that works on windows mac and linux. then merge that into the master branch and have different "channels" that you can switch between so if you wanna switch from nightly to bleeding edge you can just click a button)
