### ISSUE TITLE
Updater : Not Working

### ISSUE THREAD

**Issue by AdityaTeguh** [citra-emu/citra-bleeding-edge#35]
the updater just checking for update nor download for user

**Comment by jroweboy** [comment]
This isn't enough information to look more into this issue. You'd need to provide the squirrel.log for me to know whats wrong.

Also its a known issue that bleeding edge doesn't not have any sort of progress bar when it updates. This will be fixed when I get around to rewriting bleeding edge. It is still updating when you click "Update" but it looks like its doing nothing.

**Comment by JayFoxRox** [comment]
This is a bug tracker for developers of Citra.

Please use the [Citra Forum for questions and support](https://community.citra-emu.org/) instead.
Note that there is no support if you use pirated copies of the game or 3DS bios files.

---

Closed as invalid
