### ISSUE TITLE
its not working 

### ISSUE THREAD

**Issue by chungas** [citra-emu/citra-bleeding-edge#37]
as vage as that is i just needed a title, i think what my problem is the os my computer is runnung on why it wont work i'm running os windows 10 pro, build 14393.693 whenever I boot the latest citra setup it dosent run and pops up with an error  heres the suirrelsetup 

[SquirrelSetup.zip](https://github.com/citra-emu/citra-bleeding-edge/files/904271/SquirrelSetup.zip)

**Comment by RavenHome1** [comment]
github for bug tracking, please use the forums for support

https://community.citra-emu.org/

**Comment by jroweboy** [comment]
@RavenHome1 to be fair this is a complaint about the bleeding edge install not working :) 

but what the install logs seem to say is that you are trying to install on a 32 bit OS. citra doesn't support 32 bit OSes so you are just out of luck. If i misread that and you actually are on a 64 bit OS then let me know.

**Comment by chungas** [comment]
@jroweboy thank you for the answer, also ill to use the fourm next time  and from your answer im assuming that there isn't a version for 32 bit, however if there is a way to jerry rig it im defenetly ears, no stranger to code id just need a plan of attack

**Comment by JayFoxRox** [comment]
This is a bug tracker for developers of Citra.

Please use the [Citra Forum for questions and support](https://community.citra-emu.org/) instead.
Note that there is no support if you use pirated copies of the game or 3DS bios files.

---

Closed as invalid
