### ISSUE TITLE
Pokémon Sun and Moon

### ISSUE THREAD

**Issue by Fugglebug** [citra-emu/citra-bleeding-edge#9]
Pokémon Moon worked on the previous build of Citra, but is not now. It crashes upon loading the ROM when it would load it perfectly last night.

![citra](https://cloud.githubusercontent.com/assets/23719550/20596544/ea8e0c78-b2a3-11e6-813c-1c3f0b37756c.PNG)

**Comment by Fugglebug** [comment]
Kidding. Pokémon Moon works if you turn off the frame limiter. Weird.

**Comment by jroweboy** [comment]
@Fugglebug frame limiter is the cause, yeah. The author was testing out some changes to try to get the framelimiter to work properly with games that aren't 60 fps
